### PR TITLE
feat: refactor

### PR DESCRIPTION
**Pull request by thejullius**

### CODE REVIEW

**Comment by rtarantelli** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/models/Reaction.js  2
- src/models/Message.js  1
- src/models/Score.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/impulsonetwork/atena/pullRequest?prid=5156979&bid=16934834)

**Comment by rtarantelli** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- tests/mocks/factory.js  4
- src/models/Message.js  1
- tests/index.test.js  1
- src/models/Reaction.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/impulsonetwork/atena/pullRequest?prid=5156979&bid=16934834)

**Comment by rtarantelli** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/models/Message.js  1
- tests/mocks/factory.js  4
- tests/index.test.js  1
- src/database/Mongo.js  1
- src/models/Reaction.js  1
- tests/utils.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/impulsonetwork/atena/pullRequest?prid=5156979&bid=16934834)

**Comment by rtarantelli** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/database/Mongo.js  1
- tests/mocks/factory.js  4
- tests/index.test.js  1
- tests/utils.js  1
- src/models/Message.js  1
- src/models/Reaction.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/impulsonetwork/atena/pullRequest?prid=5156979&bid=16934834)

**Comment by rtarantelli** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/models/Message.js  1
- tests/mocks/factory.js  4
- src/database/Mongo.js  1
- src/models/Reaction.js  1
- tests/index.test.js  1
- tests/utils.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/impulsonetwork/atena/pullRequest?prid=5156979&bid=16934834)

**Comment by rtarantelli** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/controllers/ScoreController.js  2
- src/models/Reaction.js  1
- src/database/Mongo.js  1
- src/models/Message.js  1
- tests/index.test.js  1
- tests/mocks/factory.js  4
- tests/utils.js  1
- src/controllers/AchievementController.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/impulsonetwork/atena/pullRequest?prid=5156979&bid=16934834)

**Comment by rtarantelli** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/controllers/ScoreController.js  4
- tests/utils.js  1
- tests/index.test.js  1
- src/models/Message.js  1
- src/models/Reaction.js  1
- tests/mocks/factory.js  4
- src/controllers/AchievementController.js  2
- src/database/Mongo.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/impulsonetwork/atena/pullRequest?prid=5156979&bid=16934834)

**Comment by rtarantelli** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/database/Mongo.js  1
- tests/index.test.js  1
- src/controllers/ScoreController.js  2
- tests/mocks/factory.js  4
- src/models/Message.js  1
- src/controllers/AchievementController.js  2
- src/models/Reaction.js  1
- tests/utils.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/impulsonetwork/atena/pullRequest?prid=5156979&bid=16934834)

**Comment by rtarantelli** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/controllers/AchievementController.js  2
- tests/index.test.js  1
- src/controllers/RankingController/index.js  2
- src/controllers/ScoreController.js  6
- src/models/Message.js  1
- tests/utils.js  1
- src/database/Mongo.js  1
- tests/mocks/factory.js  4
- src/models/Reaction.js  1
- src/routes/miner.js  1
- src/routes/api.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/impulsonetwork/atena/pullRequest?prid=5156979&bid=16934834)

**Comment by rtarantelli** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/database/Mongo.js  1
- src/controllers/RankingController/index.js  2
- tests/index.test.js  1
- src/routes/api.js  1
- src/models/Reaction.js  1
- src/models/Message.js  1
- tests/mocks/factory.js  4
- tests/utils.js  1
- src/routes/miner.js  1
- src/controllers/BotController.js  2
- src/controllers/AchievementController.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/impulsonetwork/atena/pullRequest?prid=5156979&bid=16934834)

**Comment by rtarantelli** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- tests/mocks/factory.js  4
- src/controllers/BotController.js  2
- src/models/Reaction.js  1
- src/models/Message/schema.js  1
- src/controllers/AchievementController.js  2
- tests/index.test.js  1
- src/routes/api.js  1
- src/routes/miner.js  1
- src/controllers/RankingController/index.js  2
- src/database/Mongo.js  1
- tests/utils.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/impulsonetwork/atena/pullRequest?prid=5156979&bid=16934834)

**Comment by rtarantelli** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/controllers/BotController.js  2
- tests/index.test.js  1
- src/controllers/RankingController/index.js  2
- src/database/Mongo.js  1
- src/controllers/AchievementController.js  2
- src/routes/miner.js  1
- src/models/Reaction.js  1
- src/models/Message/schema.js  1
- tests/utils.js  1
- src/routes/api.js  1
- tests/mocks/factory.js  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/impulsonetwork/atena/pullRequest?prid=5156979&bid=16934834)

**Comment by rtarantelli** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/controllers/AchievementController.js  2
- src/routes/api.js  1
- src/controllers/BotController.js  2
- src/models/Message/schema.js  1
- tests/utils.js  1
- src/database/Mongo.js  1
- src/routes/miner.js  1
- src/controllers/RankingController/index.js  2
- tests/index.test.js  1
- tests/mocks/factory.js  4
- src/models/Reaction.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/impulsonetwork/atena/pullRequest?prid=5156979&bid=16934834)

**Comment by rtarantelli** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/routes/api.js  1
- src/controllers/RankingController/index.js  2
- src/controllers/AchievementController.js  2
- tests/index.test.js  1
- src/models/Message/schema.js  1
- src/controllers/BotController.js  2
- src/models/Reaction.js  1
- src/routes/miner.js  1
- tests/mocks/factory.js  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/impulsonetwork/atena/pullRequest?prid=5156979&bid=16934834)

**Comment by rtarantelli** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/routes/miner.js  1
- src/routes/api.js  1
- src/controllers/BotController.js  2
- tests/index.test.js  1
- src/models/Reaction.js  1
- tests/mocks/factory.js  4
- src/controllers/RankingController/index.js  2
- src/controllers/AchievementController.js  2
- src/models/Message/schema.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/impulsonetwork/atena/pullRequest?prid=5156979&bid=16934834)

**Comment by rtarantelli** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- tests/mocks/factory.js  4
- src/controllers/RankingController/index.js  2
- src/controllers/AchievementController.js  2
- src/models/Message/schema.js  1
- src/controllers/BotController.js  2
- src/routes/miner.js  1
- tests/index.test.js  1
- src/models/Reaction.js  1
- src/routes/api.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/impulsonetwork/atena/pullRequest?prid=5156979&bid=16934834)

**Comment by rtarantelli** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/models/Message/schema.js  1
- src/models/Reaction.js  1
- tests/mocks/factory.js  4
- src/controllers/RankingController/index.js  2
- src/controllers/AchievementController.js  2
- src/routes/miner.js  1
- src/controllers/BotController.js  2
- tests/index.test.js  1
- src/routes/api.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/impulsonetwork/atena/pullRequest?prid=5156979&bid=16934834)

**Comment by rtarantelli** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/models/Reaction.js  1
- tests/index.test.js  1
- src/controllers/RankingController/index.js  2
- tests/mocks/factory.js  4
- src/routes/miner.js  1
- src/controllers/AchievementController.js  2
- src/routes/api.js  1
- src/models/Message/schema.js  1
- src/controllers/BotController.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/impulsonetwork/atena/pullRequest?prid=5156979&bid=16934834)

**Comment by rtarantelli** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/controllers/RankingController/index.js  2
- tests/index.test.js  1
- tests/mocks/factory.js  4
- src/controllers/AchievementController.js  2
- src/models/Reaction.js  1
- src/routes/miner.js  1
- src/models/Message/schema.js  1
- src/controllers/BotController.js  2
- src/routes/api.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/impulsonetwork/atena/pullRequest?prid=5156979&bid=16934834)

**Comment by rtarantelli** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/controllers/BotController.js  2
- tests/index.test.js  1
- src/routes/api.js  1
- src/routes/miner.js  1
- src/models/Reaction.js  1
- src/models/Message/schema.js  1
- src/controllers/RankingController/index.js  2
- tests/mocks/factory.js  4
- src/controllers/AchievementController.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/impulsonetwork/atena/pullRequest?prid=5156979&bid=16934834)

**Comment by rtarantelli** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/controllers/AchievementController.js  2
- src/routes/api.js  1
- src/controllers/RankingController/index.js  2
- src/models/Reaction.js  1
- tests/mocks/factory.js  4
- src/models/Message/schema.js  1
- src/controllers/BotController.js  2
- src/routes/miner.js  1
- tests/index.test.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/impulsonetwork/atena/pullRequest?prid=5156979&bid=16934834)

**Review by omarciovsena — APPROVED** [review]

**Pull request merged**
