### PR TITLE
Mecânica de ganho do Plano Pro

### PR DESCRIPTION
**Pull request by lazaroalvarenga**

### CODE REVIEW

**Comment by lazaroalvarenga** [comment]
#290

**Review by goldblade — COMMENTED** [review]
do you think about should add some tests?

**Comment by lazaroalvarenga** [comment]
> do you think about should add some tests?

which are? I'll call u by DM

**Review by goldblade — APPROVED** [review]
Aprovado para testar em staging, faltando os testes unitários

**Pull request merged**
