### PR TITLE
chore: send achievement

### PR DESCRIPTION
**Pull request by thejullius**

### CODE REVIEW

**Comment by rtarantelli** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones removed
==============
+ src/controllers/AchievementController.js  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/impulsonetwork/atena/pullRequest?prid=5506120&bid=18045586)

**Comment by rtarantelli** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones removed
==============
+ src/controllers/AchievementController.js  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/impulsonetwork/atena/pullRequest?prid=5506120&bid=18045586)

**Comment by rtarantelli** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones removed
==============
+ src/controllers/AchievementController.js  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/impulsonetwork/atena/pullRequest?prid=5506120&bid=18045586)

**Comment by rtarantelli** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/routes/api.js  1
         

Clones removed
==============
+ src/controllers/AchievementController.js  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/impulsonetwork/atena/pullRequest?prid=5506120&bid=18045586)

**Review by omarciovsena — APPROVED** [review]

**Review by omarciovsena — DISMISSED** [review]

**Comment by rtarantelli** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/routes/api.js  1
         

Clones removed
==============
+ src/controllers/AchievementController.js  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/impulsonetwork/atena/pullRequest?prid=5506120&bid=18045586)

**Comment by rtarantelli** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/routes/api.js  1
         

Clones removed
==============
+ src/controllers/AchievementController.js  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/impulsonetwork/atena/pullRequest?prid=5506120&bid=18045586)

**Comment by rtarantelli** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/routes/api.js  1
         

Clones removed
==============
+ src/controllers/AchievementController.js  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/impulsonetwork/atena/pullRequest?prid=5506120&bid=18045586)

**Comment by rtarantelli** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/routes/api.js  1
         

Clones removed
==============
+ src/controllers/AchievementController.js  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/impulsonetwork/atena/pullRequest?prid=5506120&bid=18045586)

**Pull request merged**
